name: manager_bell
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.1.1
  flutter_local_notifications: 17.1.2   # << QUEDA FIJA
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# ---------------------------------------------------------------
#  OVERRIDE para obligar a 14.1.1 sin causar conflicto
# ---------------------------------------------------------------
dependency_overrides:
  flutter_local_notifications: 17.1.2

# ---------------------------------------------------------------
#  ICONO DE LA APP
# ---------------------------------------------------------------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

# ---------------------------------------------------------------
#  SPLASH SCREEN
# ---------------------------------------------------------------
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/splash/splash.png
