name: manager_bell
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  shared_preferences: ^2.1.1

  # ðŸ‘‡ VERSIÃ“N COMPATIBLE Y ESTABLE
  flutter_local_notifications: 19.5.0

  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/splash/splash.png
