name: manager_bell
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Estado y gestión de datos
  provider: ^6.0.5

  # Permisos
  permission_handler: ^11.0.1

  # HTTP y comunicación
  http: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.0.17
  # Identificadores únicos
  uuid: ^4.5.2

  # Almacenamiento local
  shared_preferences: ^2.5.4

  # Notificaciones locales
  flutter_local_notifications: ^19.5.0
  flutter_local_notifications_linux: ^6.0.0

  # Internacionalización / manejo de fechas
  intl: ^0.20.2
  timezone: ^0.10.1

  # Íconos
  cupertino_icons: ^1.0.8

  # Utilidades de colores
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/splash/splash.png
